"""Message parent_message_id

Revision ID: b212cf91d0da
Revises: 6029f38129d1
Create Date: 2024-06-26 18:16:57.092922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b212cf91d0da'
down_revision: Union[str, None] = '6029f38129d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_message_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_parent_message_id', 'messages', ['parent_message_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parent_message_id', type_='foreignkey')
        batch_op.drop_column('parent_message_id')

    # ### end Alembic commands ###
